#!/bin/bash

[ -p /tmp/.update_status ] || mkfifo /tmp/.update_status

# wait until were connected
until ping -c 1 'archlinux.org' >/dev/null 2>&1; do
	sleep 10
done

# loop and dump info to the pipe
while true; do
	if (( ( COUNT = $(dnf check-update 2>/dev/null | grep -c "\supdates") ) > 0 )); then
		echo "PKG: $COUNT" >/tmp/.update_status
		# recheck when the log is written to or after 1.5 hours
		inotifywait -q -q -t 5000 -e close_write /var/log/dnf.rpm.log
		sleep 10
	else
		echo "PKG: $COUNT" >/tmp/.update_status
		sleep 5000 # only do a recheck every 1.5 hours to save some cpu time
	fi
done
