#!/usr/bin/env bash

pictures_dir="$(xdg-user-dir backgrounds 2> /dev/null)"
slice="${pictures_dir:-$HOME/backgrounds}/slice.png"
image=$(mktemp --tmpdir --suffix=.png lock.XXXXXXXXXX)
#trap 'rm -f "$image"' SIGINT SIGTERM EXIT

screens=$(xrandr | grep -Eo '[0-9]+x[0-9]+\+[0-9]+\+[0-9]+')
declare -a lines

for screen in $screens; do
    read -r W H X Y < <(sed 's/[^0-9]/ /g' <<< "$screen")
    lines+=(\( "$slice"
        -resize "${W}x1080!"
        -geometry "+${X}+${Y}" \)
        -composite -matte)
done

maim -u -m 1 $image
convert $image -scale 10% -scale 1000% $image
#    -fill "#282828" -colorize 1% \
#    ${lines[*]} "$image"
i3lock -i $image
