#!/usr/bin/env bash

#bg=272727
#fg=CACACA
#ac=f4511e
#mf=383838

image=$(mktemp --tmpdir --suffix=.png lock.XXXXXXXXXX)
trap 'rm -f "$image"' SIGINT SIGTERM EXIT

#screens=$(xrandr | grep -Eo '[0-9]+x[0-9]+\+[0-9]+\+[0-9]+')
#declare -a lines

maim -u -d 0.2 \
    | convert png:- -scale 10% -scale 1000% "$image"

i3lock \
    --image="$image" \
    --ignore-empty-password
