#!/bin/bash

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 5 <<< " Lock| Suspend| Logout| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) ~/.scripts/lock ;;
                *Suspend) systemctl suspend ;;
                *Logout) loginctl terminate-user "$USER" ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff ;;
            esac
